on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_all:
    strategy:
      matrix:
        os:
          - freebsd # self-hosted FreeBSD runner
          - ubuntu-latest
          - macos-latest
          - windows-latest
    name: Test all on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: purefns/setup-zig@main
        with:
          version: 0.13.0
      - run: zig build test
